### ISSUE TITLE
DKMS not required for Jetson camera driver build

### ISSUE THREAD

**Issue by QQting** [tier4/tier4_automotive_hdr_camera#44]
Hi guys,

I noticed you have changed the DKMS configuration to build camera driver.
https://github.com/tier4/tier4_automotive_hdr_camera/blob/9ebee0c09654e3df19576b9f0000a076d66c197e/pkg/dkms.conf#L4-L5

However, this change may cause compilation error due to the camera driver will install generic kernel headers automatically:

![Image](https://github.com/user-attachments/assets/17b8a1be-061b-49e9-9804-f543a994399b)

<img width="921" height="396" alt="Image" src="https://github.com/user-attachments/assets/be77427e-997d-49c0-a453-8567ec242fde" />

Since kernel upgrades involve re-flashing the BSP image, DKMS is not needed for the camera driver.

**Comment by luvwinnie** [comment]
Hi @QQting, sorry for sudden message to you.

Currently I'm trying to work with Jetson AGX Orin 64GB Developerkit, but it seems like I can't get the camera work with Jetpack 6.2.1 L4T36.

I wondering that you are working with RQX-59G, may I ask how did you check to make it compatible to specific driver?

**Comment by QQting** [comment]
> Hi [@QQting](https://github.com/QQting), sorry for sudden message to you.
> 
> Currently I'm trying to work with Jetson AGX Orin 64GB Developerkit, but it seems like I can't get the camera work with Jetpack 6.2.1 L4T36.
> 
> I wondering that you are working with RQX-59G, may I ask how did you check to make it compatible to specific driver?

- Build and install driver without errors.
- Tier4_xxx.dtbo can successfully merged with my sysytem dtb file by using `fdtoverlay`.
- Reboot, check all the necessary .ko drivers are successfully loaded by checking `lsmod` and `dmesg`.
- Check video nodes are succesfully generated by typing `ls /dev/video*`
- Use 'v4l2-ctl' or 'gst-launch' to test camera streaming
