### ISSUE TITLE
v2.1.0 installation fails on L4T 32.6.1 (Kernel 4.9) due to use of `timer_setup()`

### ISSUE THREAD

**Issue by zoncoen** [tier4/tier4_automotive_hdr_camera#42]
I am unable to install the v2.1.0 device driver on ADLINK ROSCube RQX-58G (v2.0.0 installs successfully).

## Environment

Hardware: ADLINK ROSCube RQX-58G
L4T Version: 32.6.1
Kernel Version: 4.9.253-rqx58g
Driver Version: v2.1.0 (fails), v2.0.0 (succeeds)

## Steps to Reproduce

Following the [official installation guide](https://tier4.github.io/edge-auto-docs/getting_started/getting_started_guide_ROSCube.html#camera-driver-installation) for the RQX-58G results in a build failure.

```
$ sudo apt install /path/to/tier4-camera-gmsl_2.0.0_arm64.deb
...
Setting up tier4-camera-gmsl (2.1.0) ...
Loading new tier4-camera-gmsl-2.1.0 DKMS files...
Building for 4.9.253-rqx58g
Building for architecture arm64
Building initial module for 4.9.253-rqx58g
ERROR (dkms apport): kernel package linux-headers-4.9.253-rqx58g is not supported
Error! Bad return status for module build on kernel: 4.9.253-rqx58g (arm64)
Consult /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/make.log for more information.
Removing old tier4-camera-gmsl-2.1.0 DKMS files...
```

## Detailed Error Log

Here is the detailed error message from `make.log`. The key error seems to be `implicit declaration of function ‘timer_setup’` in the file [`tier4-max9295.c`](https://github.com/tier4/tier4_automotive_hdr_camera/blob/9ebee0c09654e3df19576b9f0000a076d66c197e/src/tier4-camera-gmsl/tier4-max9295.c#L838).

```
$ cat /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/make.log
DKMS make.log for tier4-camera-gmsl-2.1.0 for kernel 4.9.253-rqx58g (aarch64)
2025年  7月 28日 月曜日 14:04:46 JST
Makefile.dkms:41: L4T_RELEASE_MAIN  = R32
Makefile.dkms:42: L4T_RELEASE_MAJOR = 6
Makefile.dkms:43: L4T_RELEASE_MINOR = 1
Makefile.dkms:45: dt_compatible = nvidia,galennvidia,jetson-xaviernvidia,p2822-0000+p2888-0001nvidia,tegra194
Makefile.dkms:46: Orin_Compatible_word = p3737-0000+p3701-0000nvidia
Makefile.dkms:70: MODEL = ROScube-Xavier
Makefile.dkms:305: L4T_RELEASE    = R32.6.1
Makefile.dkms:306: KERNELRELEASE  = 4.9.253-rqx58g
Makefile.dkms:307: KERNEL_SRC_DIR = /lib/modules/4.9.253-rqx58g/build/
Makefile.dkms:309: TARGET_ISX021_DTS               = tier4-isx021-gmsl-device-tree-overlay-roscube-r325x
Makefile.dkms:310: TARGET_IMX490_DTS               = tier4-imx490-gmsl-device-tree-overlay-roscube-r325x
Makefile.dkms:311: TARGET_IMX728_DTS               = tier4-imx728-gmsl-device-tree-overlay-roscube-r325x
Makefile.dkms:312: TARGET_ISX021_IMX490_IMX728_DTS = tier4-isx021-imx490-gmsl-device-tree-overlay-roscube-r325x
Makefile.dkms:313: TARGET_ISX021_IMX490_IMX728_DTS = tier4-isx021-imx490-imx728-gmsl-device-tree-overlay-roscube-r325x
install -d /lib/firmware
cp -f /usr/src/tier4-camera-gmsl-2.1.0/tier4-isx021.bin /lib/firmware/tier4-isx021.bin
make -C /lib/modules/4.9.253-rqx58g/build/ ARCH=arm64 M=/var/lib/dkms/tier4-camera-gmsl/2.1.0/build src=/var/lib/dkms/tier4-camera-gmsl/2.1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.253-rqx58g'
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-fpga.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-gw5300.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-imx490.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-imx728.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-isx021.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9295.o
  CC [M]  /var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9296.o
/var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9295.c: In function ‘tier4_max9295_probe’:
/var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9295.c:838:2: error: implicit declaration of function ‘timer_setup’; did you mean ‘ktime_set’? [-Werror=implicit-function-declaration]
  timer_setup(&priv->hw_monitor_timer, hw_monitor_timer_callback,
  ^~~~~~~~~~~
  ktime_set
cc1: some warnings being treated as errors
scripts/Makefile.build:341: recipe for target '/var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9295.o' failed
make[2]: *** [/var/lib/dkms/tier4-camera-gmsl/2.1.0/build/tier4-max9295.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1655: recipe for target '_module_/var/lib/dkms/tier4-camera-gmsl/2.1.0/build' failed
make[1]: *** [_module_/var/lib/dkms/tier4-camera-gmsl/2.1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.253-rqx58g'
Makefile.dkms:337: recipe for target 'modules' failed
make: *** [modules] Error 2
```

## Analysis
I believe this issue is caused by a code change introduced v2.1.0 that is incompatible with the kernel version.

The driver v2.1.0 appears to have introduced [a call to the `timer_setup()` function](https://github.com/tier4/tier4_automotive_hdr_camera/commit/04e1785fd72fa916da2bb4802ef410c3afa55605). This function was officially added in Linux kernel v4.15. However, the target system (L4T 32.6.1) runs on kernel version 4.9.253, which does not include this function.

This explains why driver v2.1.0 cannot be compiled on this platform, while v2.0.0 could be installed without this issue.
